### PR TITLE
Mailing library - MailKit replaced with standard SmtpClient

### PR DESCRIPTION
**Pull request by tomasherceg**
I have removed current `IMailSenders` depending on MailKit package and replaced them with standard `System.Net.Mail.SmtpClient` which is already available in .NET Core 2.0.

As far as I know, we don't use these classes in any projects, and even if we do, the migration to `SmtpClientMailSender` should not be difficult - it is just one change in startup.

The default `SmtpClient` supports pickup directories, so we can have just one mail sender. In classic ASP.NET, it can be configured via web.config. For ASP.NET Core, I was thinking of providing a configuration object that could be easily mapped from `appsettings.json`. Do you think it is a good idea?

### CODE REVIEW

**Comment by ridercz** [comment]
I ended up writing separate library for mailing purposes, see my Altairis.Services.Mailing project, which supports System.Net.Mail, MailKit and SendGrid ATM. 

I intend to write mail templating engine over it. Maybe replace the mailing part with my library? I think it does not belong to architecture toolkit anyway...

**Comment by tomasherceg** [comment]
Do you think that the templating engine is necessary? I find it less and less useful over time, because both SendGrid and MailChimp have online editors where you can build your own templates with placeholders, and then use REST API to substitute values and send e-mails using these templates. No programming required and the templates are easy to change. 
I know that you don't like HTML e-mail, but these services remove practically all PITA coming with them - you build the template using pre-defined blocks, which are tested in all mail clients and display correctly. They deal with responsiveness and other things. They generate quite good plain-text versions of the e-mails as well, and solve things like unsubscribing, automatic identification of invalid e-mail adresses and so on. 
So I am thinking whether the templating engine has some significant advantages.

**Comment by ridercz** [comment]
The approach you mentioned is good for mass mailings, I'm thinking more of transactional mail. 

For transactional messages I think it's important to be independent on provider-specific formatting.

Don't worry, you bullied me into supporting HTML messages already :p

**Comment by Melchy** [comment]
I don't think that we should merge this. According to official [documentation ](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=netcore-3.0#remarks) is System.Net.Mail.SmtpClient obsolete.

**Comment by tomasherceg** [comment]
Good catch, I wasn't aware of the fact that using the API is not recommended any more.

Let's do it differently then:
* We should keep `Riganti.Utils.Infrastructure.Services.Mailing` package with only DTOs and shared classes for all mailing implementations.
* We should add `Riganti.Utils.Infrastructure.Services.Mailing.MailKit` package that will contain the `MimeKit` implementation.
* We should add `Riganti.Utils.Infrastructure.Services.Mailing.SmtpClient` package that will contain the `SmtpClient` implementation - I'd like to have it to have backwards compatibility - some projects depend on features like mail pickup directory and MailKit generates the e-mails in a different format.
* We should also rename `Amazon.SES` package to `Riganti.Utils.Infrastructure.Services.Mailing.AmazonSes` and `SendGrid` to `Riganti.Utils.Infrastructure.Services.Mailing.SendGrid`.

Also, the `SendGrid` package uses `Subtitutions` which are now deprecated. We should upgrade the package and update the Template object to contain the Template ID and a TemplateData object.

And finally, I'd rename `ITemplate` to `IMailingTemplate` so the name is more specific.

**Pull request closed without merging**
