### PR TITLE
Async facades

### PR DESCRIPTION
**Pull request by Leeemons**
I made async facades because the other components(Repository, Query etc.) have async methods.

### CODE REVIEW

**Comment by luboshl** [comment]
It's not good idea to call async method from sync version of method and then lock the thread with Wait. I would prefer to call sync methods of repository from sync methods of facade and async method of repository from async method of facade.

For example `CrudFacadeBase.GetDetail` should call `Repository.GetById` (as it was before) and `CrudFacadeBase.GetDetailAsync` should call `Repository.GetByIdAsync`. Then you don't need to wait anything.

And the other reason is that now you change the current behavior of facades (by changing current sync version of methods) although you only want to add async versions of method.

It's true that most of the code will be duplicate. Yes, it will :)

**Comment by luboshl** [comment]
I haven't noticed that you create new thread with `TaskFactory.StartNew` (why not `Task.Run`?) to run async method from sync method. But still I think it's not a good practise, if not necessary. The repository has both sync and async methods so I would use the corresponding one for each.

**Comment by Leeemons** [comment]
`Task.Run`
 is equivalent to
```
Task.Factory.StartNew(someAction, 
    CancellationToken.None, TaskCreationOptions.DenyChildAttach, TaskScheduler.Default)
```
and you can set more options for StartNew than for Task.Run

**Comment by Leeemons** [comment]
It's things of opinion. Async and Sync method are exactly same except async word at end of methods. I wanted avoid duplicate code so if you need add/change/remove some logic of method, you will add the logic in one place of code.

**Comment by quigamdev** [comment]
This pattern is used in VS SDK for sync parts of extensions. It seems ok to me. The main point of this PR is to add async methods without duplication of code, overwise it is badly maintainable.

**Comment by luboshl** [comment]
After in person discussion, we decided to revert changed _sync_ version of changed methods. In this PR they were modified to be only wrappers over newly added _async_ versions, but this approach has some issues.

Will be fixed in PR #32.

**Pull request merged**
